S03 US47 work experiences
WildCodeSchool/202209-orleans-php-project-externatic pull request #104
Opened 2022-12-18 10:02 UTC by williambouet

2022-12-19 08:03 UTC, hhertout submitted a review, later dismissed

2022-12-19 08:45 UTC, sblondeau requested changes

2022-12-19 08:45 UTC, sblondeau commented on src/Controller/CandidateController.php
> +            'experiences' => $experienceRepository->findByExampleField($candidate->getId()),
non, tu les récupères direct dans ta vue en bouclant sur candidate.experiences ;-) c'est tout l'interet de Doctrine :p

2022-12-19 08:45 UTC, sblondeau commented on templates/candidate/show.html.twig
> +						<img class="profilPicture rounded-circle border my-3" src="{{ user.avatar is empty ? asset ('build/images/Placeholder-pp.png') : asset ('build/images/' ~ user.avatar ) }}" alt="Image de profil"
tu peux renommer le fichier placeholer-pp ? ce n'est pas parlant

2022-12-19 08:45 UTC, sblondeau commented on src/Controller/CandidateController.php
> +            'experiences' => $experienceRepository->findByExampleField($candidate->getId()),
en fait une fois ton login fait tu n'auras meme pas besion de récupérer candidate, ni passer user.
Depuis twig tu fais un app.user pour avoir l'utilisateur actuellement connecté
et donc tu peux faire un app.user.candidate.experiences normalement ;-)

2022-12-19 08:57 UTC, williambouet commented on src/Controller/CandidateController.php
> +            'experiences' => $experienceRepository->findByExampleField($candidate->getId()),
bien vu, je n'ai pas eu le réflex de le voir comme ça, merci

2022-12-19 10:14 UTC, hhertout commented on templates/candidate/show.html.twig
> +{% include "experience/_index.html.twig" %}
include peut-être plus haut pour profiter de la mise en page déjà mise en place ??

2022-12-19 10:14 UTC, hhertout commented on templates/experience/_index.html.twig
> +		<div class="col-md-6">
Tu n'aurais plus besoin de ces trois div du coup théoriquement

2022-12-19 10:17 UTC, hhertout commented on templates/candidate/show.html.twig
> -					<div class="row justify-content-between align-items-center">
et pourquoi pas mettre ça aussi dans un fichier include comme tu as fais pour les expériences pro pour gagner plus de lisibilité ?? (les infos perso du candidat)

2022-12-19 10:23 UTC, hhertout approved these changes

2022-12-19 10:30 UTC, hhertout approved these changes

2022-12-19 15:37 UTC, HuHoudas approved these changes

2022-12-20 07:52 UTC, sblondeau approved these changes

2022-12-20 11:02 UTC, cedriclv approved these changes

2022-12-20 15:27 UTC, merged