Us03 fonction recherche par mot cle
WildCodeSchool/202209-orleans-php-project-externatic pull request #110
Opened 2022-12-20 11:24 UTC by cedriclv

2022-12-20 13:34 UTC, hhertout commented on src/Controller/OfferController.php
> +            $offers = $offerRepository->findAll();
Si la recherche n'a pas de résultat, on prends le choix d'afficher toutes les annonces ? 
Je serais d'avis si c'est le cas, de au moins l'informer que sa recherche n'a pas eu de résultat, ce serait plus logique d'un point de vue utilisateur ? 
Pourquoi pas l'implémenter comme un message d'erreur style $error = 'Pas de résultat pour la recherche' qui te permettrai de l'afficher dans la vue twig en plus de toutes les annonces ?

2022-12-20 14:46 UTC, williambouet submitted a review, later dismissed

2022-12-20 14:49 UTC, hhertout submitted a review, later dismissed

2022-12-20 15:01 UTC, williambouet submitted a review, later dismissed

2022-12-20 15:02 UTC, hhertout submitted a review, later dismissed

2022-12-20 15:55 UTC, sblondeau requested changes

2022-12-20 15:55 UTC, sblondeau commented on src/Form/SearchOfferType.php
> +            ->add('search', SearchType::class)
setMethod GET

2022-12-20 15:55 UTC, sblondeau commented on src/Form/SearchOfferType.php
> +            // Configure your form options here
enlever le csrf token et renommer les champs du form (voir ce que je viens de faire en LC)

2022-12-20 15:55 UTC, sblondeau commented on src/Controller/OfferController.php
> +            $keyWord = $form->getData();
tu es sur que ça marche là ? ton form->getData() devrait te renvoyer plutot un tableau et non direct une string

2022-12-22 08:12 UTC, williambouet commented on templates/offer/index.html.twig
>  {% endblock %}
Je crois que tu as un souci avec ton title, le {{ parent() }} se retrouve dans le bloc stylesheets, alors qu'il devrait être dans le block title sous forme {{ parent() ' | Offres' }}

2023-01-03 11:27 UTC, hhertout submitted a review, later dismissed

2023-01-03 11:35 UTC, sblondeau requested changes

2023-01-03 11:35 UTC, sblondeau commented on templates/offer/index.html.twig
> +    <div>{{ form_label(form.search, null, { label: 'Votre Recherche', label_attr: { class: 'col-form-label' } }) }}</div>
faire un form_row(form.search) ne serait-il pas plus simple ? 
la traduction du label peut se faire dans la classe de form direct

2023-01-03 11:35 UTC, sblondeau commented on src/Controller/OfferController.php
> +    #[Route('/', name: 'index', methods: ['GET','POST'])]
le POST est il utile ici ? vu que ton form est en GET

2023-01-03 14:59 UTC, hhertout approved these changes

2023-01-04 08:14 UTC, sblondeau approved these changes

2023-01-04 08:14 UTC, merged