FIX problems mobile view
WildCodeSchool/202209-orleans-php-project-externatic pull request #113
Opened 2023-01-01 10:49 UTC by williambouet

2023-01-02 08:19 UTC, hhertout submitted a review, later dismissed

2023-01-02 08:42 UTC, sblondeau requested changes

2023-01-02 08:42 UTC, sblondeau commented on templates/candidate/_profil.html.twig
> +	<div class="row mb-1">
il faudrait plutot utiliser la balise dl (dd / dt) dans ce cas, c'est mieux sémantiquement parlant
https://developer.mozilla.org/fr/docs/Web/HTML/Element/dl
et vous pouvez mettre un style css générique dans sur ces balises pour éviter d'avoir à mettre des align-self partout ;-)

2023-01-02 08:42 UTC, sblondeau commented on templates/education/_index.html.twig
>  		<div class="row">
idem pour les dl, partout où c'est nécessaire

2023-01-02 08:42 UTC, sblondeau commented on templates/experience/_index.html.twig
> +			<span class="d-none d-md-inline">professionnelles</span>
pas terrible de masquer un mot pour que ça rentre en mobile :/ 
faudrait me montrer votre rendu actuel pour voir si on peut trouver une autre solution

2023-01-02 10:53 UTC, hhertout approved these changes

2023-01-03 10:49 UTC, HuHoudas submitted a review, later dismissed

2023-01-03 11:24 UTC, sblondeau approved these changes

2023-01-03 15:36 UTC, hhertout approved these changes

2023-01-04 08:15 UTC, merged