S03US12 added preview avatar
WildCodeSchool/202209-orleans-php-project-externatic pull request #114
Opened 2023-01-01 11:13 UTC by williambouet

2023-01-02 09:07 UTC, hhertout submitted a review, later dismissed

2023-01-02 12:31 UTC, hhertout approved these changes

2023-01-02 14:47 UTC, Zakari-B requested changes

2023-01-02 14:47 UTC, Zakari-B commented on src/Form/RegistrationFormType.php
> +                /* 'attr' => ['id' => 'thumb'] */
Pas de commentaires dans le code envoyé en PR.

2023-01-03 09:58 UTC, sblondeau approved these changes

2023-01-03 09:58 UTC, merged