S3US40 Offer Creation
WildCodeSchool/202209-orleans-php-project-externatic pull request #122
Opened 2023-01-02 20:44 UTC by hhertout

2023-01-03 10:09 UTC, williambouet submitted a review, later dismissed

2023-01-03 10:15 UTC, HuHoudas submitted a review, later dismissed

2023-01-03 10:39 UTC, williambouet submitted a review, later dismissed

2023-01-03 11:32 UTC, sblondeau requested changes

2023-01-03 11:32 UTC, sblondeau commented on src/Controller/OfferController.php
> +            $offer->setCreatedAt($date);
tu le mets déjà dans le construct, pas la peine de resetter la date ici non ?

2023-01-03 11:32 UTC, sblondeau commented on src/Controller/OfferController.php
> +            $offer->setIsImportant(false);
idem ici tu set la propriété à false par défaut dans ton Entity (au lieu de null) ça devrait t'éviter d'avoir à le setter ici

2023-01-03 11:32 UTC, sblondeau commented on src/Form/OfferType.php
> +            ->add('annualWage', IntegerType::class, [
je sais pas si ça vaut le coup ici, mais il existe un MoneyType dans symfony
https://symfony.com/doc/current/reference/forms/types/money.html

2023-01-03 11:32 UTC, sblondeau commented on templates/dashboard_layout.html.twig
> +			{% include './component/_footer.html.twig' %}
pas la peine de mettre ./ devant

2023-01-03 15:06 UTC, HuHoudas submitted a review, later dismissed

2023-01-04 08:15 UTC, sblondeau submitted a review, later dismissed

2023-01-04 10:43 UTC, williambouet approved these changes

2023-01-04 10:44 UTC, merged