US28 => vue de toutes les offres sur le Dashboard
WildCodeSchool/202209-orleans-php-project-externatic pull request #124
Opened 2023-01-03 11:31 UTC by hhertout

2023-01-03 11:55 UTC, HuHoudas approved these changes

2023-01-04 08:16 UTC, sblondeau requested changes

2023-01-04 08:16 UTC, sblondeau commented on src/Controller/OfferController.php
> +            'offers' => $offerRepository->findAll(),
peut-etre trier en fonction de la date ? ou d'un autre critère ?

2023-01-04 10:41 UTC, williambouet approved these changes

2023-01-04 10:45 UTC, Zakari-B approved these changes

2023-01-04 10:45 UTC, merged