S03US06_Login/Logout
WildCodeSchool/202209-orleans-php-project-externatic pull request #125
Opened 2023-01-03 11:54 UTC by HuHoudas

2023-01-03 15:05 UTC, hhertout submitted a review, later dismissed

2023-01-04 08:23 UTC, sblondeau requested changes

2023-01-04 08:23 UTC, sblondeau commented on src/Controller/LoginController.php
> +    #[Route('/login', name: 'app_login')]
/connexion plutot ?

2023-01-04 08:23 UTC, sblondeau commented on src/Controller/SecurityController.php
> +    #[Route('/logout', name: 'app_logout', methods: ['GET'])]
/deconnexion

2023-01-04 08:23 UTC, sblondeau commented on templates/login/index.html.twig
> +			<button type="submit" class="btn btn-primary mt-3 align-self-end">login</button>
traduire login

2023-01-04 08:23 UTC, sblondeau commented on templates/login/index.html.twig
> +			<label for="password" class="mt-3 align-self-start">Password:</label>
traduction password
espace entre le label et les ":"

2023-01-04 10:32 UTC, hhertout submitted a review, later dismissed

2023-01-04 10:37 UTC, williambouet commented on templates/login/index.html.twig
> +			<button type="submit" class="btn btn-primary mt-3 align-self-end">Connection </button>
Connexion avec 'x'

2023-01-04 11:05 UTC, hhertout approved these changes

2023-01-04 11:08 UTC, williambouet submitted a review, later dismissed

2023-01-04 12:23 UTC, sblondeau requested changes

2023-01-04 12:23 UTC, sblondeau commented on src/Controller/SecurityController.php
> +    #[Route('/deconnection', name: 'app_logout', methods: ['GET'])]
deconnexion

2023-01-04 12:23 UTC, sblondeau commented on templates/login/index.html.twig
> +			<label for="username" class="align-self-start">Email: </label>
Email : (espace avant les deux points en français)

2023-01-04 13:17 UTC, hhertout approved these changes

2023-01-04 14:46 UTC, hhertout approved these changes

2023-01-04 15:05 UTC, merged