US07 part3 => Adding search bar to home
WildCodeSchool/202209-orleans-php-project-externatic pull request #163
Opened 2023-01-05 15:12 UTC by hhertout

2023-01-05 15:15 UTC, HuHoudas submitted a review, later dismissed

2023-01-05 15:34 UTC, sblondeau requested changes

2023-01-05 15:41 UTC, HuHoudas approved these changes

2023-01-05 15:53 UTC, sblondeau requested changes

2023-01-05 15:53 UTC, sblondeau commented on templates/home/index.html.twig
> +			<div class=" bg-light p-5 rounded">
p-3 p-md-5 rendrait mieux :p

2023-01-05 17:20 UTC, hhertout commented on templates/home/index.html.twig
> +			<div class=" bg-light p-5 rounded">
C'est encore mieux avec un py-4 px-3 p-md-5 ! :D

2023-01-05 18:15 UTC, williambouet approved these changes

2023-01-06 07:48 UTC, sblondeau submitted a review, later dismissed

2023-01-06 08:00 UTC, williambouet approved these changes

2023-01-06 08:19 UTC, Zakari-B approved these changes

2023-01-06 08:19 UTC, merged