Us30 offres candidat
WildCodeSchool/202209-orleans-php-project-externatic pull request #182
Opened 2023-01-07 09:11 UTC by cedriclv

2023-01-07 09:33 UTC, hhertout submitted a review, later dismissed

2023-01-09 08:28 UTC, sblondeau requested changes

2023-01-09 08:28 UTC, sblondeau commented on src/Controller/CandidateController.php
> +    #[Route('/{id}/mes-candidatures', name: 'app_candidate_show_Offers_Applied', methods: ['GET'])]
reste tout en minuscules sur les noms de routes par cohérence et simplifie peut-etre
tu peux aussi passer app_candidate en préfixe de nom de route général au dessus de ta classe

2023-01-09 10:54 UTC, cedriclv commented on src/Controller/CandidateController.php
> +    #[Route('/{id}/mes-candidatures', name: 'app_candidate_show_Offers_Applied', methods: ['GET'])]
ok merci j'ai mis un chemin au controller

2023-01-09 11:33 UTC, hhertout approved these changes

2023-01-09 11:33 UTC, HuHoudas approved these changes

2023-01-09 13:01 UTC, sblondeau approved these changes

2023-01-09 13:01 UTC, merged