voir les candidatures en tant que consultant
WildCodeSchool/202209-orleans-php-project-externatic pull request #189
Opened 2023-01-07 16:58 UTC by cedriclv

2023-01-07 17:13 UTC, hhertout requested changes

2023-01-07 17:13 UTC, hhertout commented on src/DataFixtures/UserFixtures.php
> +            $hashedPassword = $this->passwordHasher->hashPassword($candidate, 't' . $i);
ça ne sert a rien de modifier ça, en plus ça va nous faire changer tous nos mdp déjà enregistré :(

2023-01-07 18:19 UTC, cedriclv commented on src/DataFixtures/UserFixtures.php
> +            $hashedPassword = $this->passwordHasher->hashPassword($candidate, 't' . $i);
yes c vrai mais c'est ce que j'avais dans dev justement, avec ce "t" bizarre...

2023-01-07 18:22 UTC, cedriclv commented on src/DataFixtures/UserFixtures.php
> +            $hashedPassword = $this->passwordHasher->hashPassword($candidate, 't' . $i);
en fait je ne l'ai pas changé.
je vais remettre "candidate_" comme j'avais fait initialement

2023-01-07 18:30 UTC, hhertout commented on src/DataFixtures/UserFixtures.php
> +            $hashedPassword = $this->passwordHasher->hashPassword($candidate, 't' . $i);
Ouai je pense que ce sera plus simple ;)

2023-01-07 18:31 UTC, hhertout submitted a review, later dismissed

2023-01-09 08:51 UTC, sblondeau requested changes

2023-01-09 08:51 UTC, sblondeau commented on src/Controller/RecruiterController.php
> +        $offers = $offerRepository->findAll();
un tri en fonction d'un critère ? date, importance, nom de l'entreprise....

2023-01-09 10:44 UTC, cedriclv commented on src/Controller/RecruiterController.php
> +        $offers = $offerRepository->findAll();
j'ai rajouté le tri par date

2023-01-09 11:32 UTC, hhertout approved these changes

2023-01-09 13:01 UTC, sblondeau approved these changes

2023-01-09 13:01 UTC, merged