FIX sort reverse experience
WildCodeSchool/202209-orleans-php-project-externatic pull request #190
Opened 2023-01-07 21:25 UTC by williambouet

2023-01-08 10:48 UTC, hhertout approved these changes

2023-01-09 08:45 UTC, sblondeau requested changes

2023-01-09 08:45 UTC, sblondeau commented on templates/experience/_index.html.twig
> +{% for experience in app.user.candidate.experiences|sort((a, b) => a.startDate <=> b.startDate)|reverse  %}
non c'est très compliqué ce que tu fais là
tu veux juste trier tes expériences dans la date inverse. Déjà tu n'as pas à faire de sort coté twig
ensuite coté PHP non plus, l'idéal c'est de faire des sort coté SQL (sauf cas complexe particulier)
le soucis c'est que ton $candidate->getExeperiences() ne te permet pas de préciser l'ordre. La solution est ici
https://www.doctrine-project.org/projects/doctrine-orm/en/2.13/tutorials/ordered-associations.html ;-)

2023-01-09 13:54 UTC, HuHoudas approved these changes

2023-01-09 15:48 UTC, hhertout approved these changes

2023-01-09 15:54 UTC, merged