Fix dashboard style
WildCodeSchool/202209-orleans-php-project-externatic pull request #198
Opened 2023-01-09 11:19 UTC by hhertout

2023-01-09 11:29 UTC, HuHoudas submitted a review, later dismissed

2023-01-09 11:41 UTC, Zakari-B requested changes

2023-01-09 11:41 UTC, Zakari-B commented on assets/styles/dashboard.scss
> +@import "root";
Non.

2023-01-09 11:41 UTC, williambouet approved these changes

2023-01-09 11:42 UTC, Zakari-B requested changes

2023-01-09 13:53 UTC, HuHoudas submitted a review, later dismissed

2023-01-09 15:57 UTC, HuHoudas approved these changes

2023-01-10 12:50 UTC, sblondeau approved these changes

2023-01-10 14:41 UTC, williambouet approved these changes

2023-01-10 14:46 UTC, merged