FIX authorizations
WildCodeSchool/202209-orleans-php-project-externatic pull request #252
Opened 2023-01-19 13:55 UTC by hhertout

2023-01-19 13:58 UTC, williambouet approved these changes

2023-01-19 14:41 UTC, sblondeau requested changes

2023-01-19 14:41 UTC, sblondeau commented on config/packages/security.yaml
> +        - { path: /offer/\d+$, roles: [ROLE_RECRUITER, ROLE_CANDIDATE] }
pour les 2 premieres ligne du access_control, tu tapes sur plein de routes, c'est assez généraliste. 
là l'url est beaucoup plus restreinte, une seule méthode j'ai l'impression. Autant mettre un #[IsGranted] au dessus de cette méthode

2023-01-19 14:44 UTC, hhertout commented on config/packages/security.yaml
> +        - { path: /offer/\d+$, roles: [ROLE_RECRUITER, ROLE_CANDIDATE] }
Le is_Granted  en haut de la route ne fonctionne pas avec plusieurs Rôle, j'ai tout essayer, avec [], {}, etc ...
C'est la seule méthode ou ça fonctionne.

2023-01-19 16:30 UTC, williambouet submitted a review, later dismissed

2023-01-20 09:20 UTC, HuHoudas approved these changes

2023-01-20 09:23 UTC, sblondeau approved these changes

2023-01-20 09:23 UTC, merged