Us42 part 1 => Adding géolocalisation to geoloc
WildCodeSchool/202209-orleans-php-project-externatic pull request #291
Opened 2023-01-25 13:53 UTC by hhertout

2023-01-25 14:18 UTC, sblondeau requested changes
je t'ai peut etre dit de gérer les erreurs dans une autre US, mais en fait là si tu ne le fais pas ton code va planter, c'est pas fonctionnel. 
Y a pas grand chose à ajouter pour gérer les cas basiques

2023-01-25 14:18 UTC, sblondeau commented on src/DataFixtures/OfferFixtures.php
> +            $position = $this->geolocalisation->find($location["city"], $location["postalCode"]);
pour le coup en terme de perf, je ne suis pas certain que ce soit pertinent d'appeler l'API dans les fixtures
Tu pourais créer qq villes avec des latitudes longitudes en dur dans ton tableau...
bon après si ça marche bien laisse comme ça

2023-01-25 14:18 UTC, sblondeau commented on src/Services/Geolocalisation.php
> +            $position = $response->getContent();
ton getContent ne sert à rien vu que tu as le toArray en dessous

2023-01-25 14:18 UTC, sblondeau commented on src/Services/Geolocalisation.php
> +            $position = $position["features"][0]["geometry"]["coordinates"];
faut ajouter une condition et gestion d'erreur car 
- si tu cherches une ville qui n'existe pas, tu as bien un 200 de l'API mais pas de coord

2023-01-25 14:18 UTC, sblondeau commented on src/Controller/OfferController.php
> +            $position = $geolocalisation->find($city, $postalCode);
voir comment plus bas, mais faut gérer le cas où l'API ne trouve pas la ville (erreur de frappe de l'utilisateur par exemple)
Dans ce cas tu n'auras pas $position["lng"] ou lat donc erreur 
Tu peux faire un if (empty($position)) ... je gère une erreur via un flash et je fais pas le redirect ? ou qq chose dans ce genre.
On pourrait faire sans doute plus propre, mais je pense que c'est un bon compromis. Au moins que ça ne plante pas

2023-01-25 14:22 UTC, hhertout commented on src/DataFixtures/OfferFixtures.php
> +            $position = $this->geolocalisation->find($location["city"], $location["postalCode"]);
ça marche impeccable

2023-01-25 15:20 UTC, williambouet submitted a review, later dismissed

2023-01-26 07:04 UTC, sblondeau approved these changes

2023-01-26 09:26 UTC, cedriclv approved these changes

2023-01-26 09:37 UTC, merged