US59_recruterur_appropriation_offer
WildCodeSchool/202209-orleans-php-project-externatic pull request #292
Opened 2023-01-25 14:12 UTC by cedriclv

2023-01-25 14:13 UTC, hhertout approved these changes

2023-01-25 14:24 UTC, sblondeau requested changes

2023-01-25 14:24 UTC, sblondeau commented on templates/component/_card.html.twig
> +            {% if offer.recruiter.user == app.user %}
fait juste un ternaire autour de la classe bg-xxx car ton code est identique pour le reste

2023-01-25 14:24 UTC, sblondeau commented on templates/component/_card.html.twig
> +          {% if offer.recruiter is not null %}
tu peux pas faire sauter un if avec un && ? car 3 if imbriqués c'est pas joli joli ;-)

2023-01-25 14:24 UTC, sblondeau commented on src/Form/OfferType.php
> +            ->add('recruiter', EntityType::class, [
pas sur de comprendre, tu choisis un recruiter au moment de créér une offre ? c'est pas le recruiter actuellement connecté qui est setté par défaut ?

2023-01-25 15:21 UTC, williambouet submitted a review, later dismissed

2023-01-26 09:02 UTC, hhertout approved these changes

2023-01-26 09:25 UTC, hhertout approved these changes

2023-01-26 09:25 UTC, cedriclv commented on templates/component/_card.html.twig
> +            {% if offer.recruiter.user == app.user %}
reglé car on ne peut plus avoir d'offre sans recruteur

2023-01-26 09:39 UTC, sblondeau requested changes

2023-01-26 09:39 UTC, sblondeau commented on templates/component/_card.html.twig
> +            <span class="badge badge-pill bg-primary fw-normal mx-1">{{ offer.recruiter.user.lastname }}</span>
fait plutot un ternaire juste autour de la classe bg-xxx car tout le reste est identique entre ton if et ton else

2023-01-26 09:56 UTC, cedriclv commented on templates/component/_card.html.twig
> +            <span class="badge badge-pill bg-primary fw-normal mx-1">{{ offer.recruiter.user.lastname }}</span>
yes done

2023-01-26 09:56 UTC, williambouet submitted a review, later dismissed

2023-01-26 11:38 UTC, sblondeau approved these changes

2023-01-26 14:52 UTC, merged