S05US24 notification candidate
WildCodeSchool/202209-orleans-php-project-externatic pull request #303
Opened 2023-01-26 09:44 UTC by williambouet

2023-01-26 09:44 UTC, hhertout approved these changes

2023-01-26 11:14 UTC, KevynSola approved these changes

2023-01-26 11:43 UTC, sblondeau requested changes

2023-01-26 11:43 UTC, sblondeau commented on src/Controller/CandidateController.php
> +        if (count($applications) > 0) {
fiat plutot un 
if (!$applications->isEmpty())

2023-01-26 14:52 UTC, cedriclv approved these changes

2023-01-27 07:08 UTC, sblondeau approved these changes

2023-01-27 07:08 UTC, merged