USNAVY dashboard candidate
WildCodeSchool/202209-orleans-php-project-externatic pull request #310
Opened 2023-01-27 10:05 UTC by williambouet

2023-01-27 10:05 UTC, hhertout submitted a review, later dismissed

2023-01-27 10:08 UTC, sblondeau requested changes

2023-01-27 10:08 UTC, sblondeau commented on src/Controller/CandidateController.php
> +        if (!$candidate->getExperiences()->isEmpty()) {
soit c'est purement esthétique, dans ce cas ça pourrait etre gérer dans twig
mais si le % de completion a d'autre répercutions, par ex, tu n'as pas accès à telle page si tu n'as pas remplis X% de ton profil; faut que cette logique "métier" soit mise dans un Service :-) en gros pas dans le controlleur

2023-01-27 15:22 UTC, hhertout approved these changes

2023-01-29 22:23 UTC, sblondeau approved these changes

2023-01-29 22:23 UTC, merged