US70 => Adding map to the offer show
WildCodeSchool/202209-orleans-php-project-externatic pull request #316
Opened 2023-01-29 10:21 UTC by hhertout

2023-01-29 10:39 UTC, hhertout reviewed
Tout fonctionne correctement...
ESlint est pas content parce que L est undefined. 
Sauf que le L provient du CDN de leaflet... 
Je ne peux pas l'instancier avant sinon ça casse tout... 

EDIT: plus de problème

2023-01-30 09:38 UTC, williambouet approved these changes

2023-01-30 10:35 UTC, sblondeau requested changes

2023-01-30 10:35 UTC, sblondeau commented on templates/offer/isNotLogShow.html.twig
> +{% block stylesheets %}
pas sur de comprendre la diff entre logShow et notLogShow

2023-01-30 10:35 UTC, sblondeau commented on templates/offer/isLogShow.html.twig
> +	<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.3/dist/leaflet.css" integrity="sha256-kLaT2GOSpHechhsozzB+flnD+zUyjE2LlfWPgU04xyI=" crossorigin=""/>
css on peut se passer du cdn aussi ?

2023-01-30 10:50 UTC, hhertout commented on templates/offer/isLogShow.html.twig
> +	<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.3/dist/leaflet.css" integrity="sha256-kLaT2GOSpHechhsozzB+flnD+zUyjE2LlfWPgU04xyI=" crossorigin=""/>
Malheureusement non... j'ai pas trouver la solution...

2023-01-30 10:51 UTC, hhertout commented on templates/offer/isNotLogShow.html.twig
> +{% block stylesheets %}
Une vue est spécifique si l'utilisateur est connecté ou non.
Il a trop de chose différentes entre les deux du coup refaire une vue était le plus simple et le plus compréhensible (en tout cas au début du projet).

2023-01-30 12:13 UTC, sblondeau requested changes

2023-01-30 12:13 UTC, sblondeau commented on templates/offer/isNotLogShow.html.twig
> +					<div id="map" data-longitude={{ offer.longitude }} data-latitude={{ offer.latitude }} class="w-100"></div>
comme discuté, je te laisse mettre dans des includes le max de chose possible si tu es forcé de passer par 2 vues

2023-01-30 13:32 UTC, merged