S1US05_User log & info Creation
WildCodeSchool/202209-orleans-php-project-externatic pull request #59
Opened 2022-12-12 11:33 UTC by hhertout

Fixture = OK,
Fonctional test  = OK

2022-12-12 11:35 UTC, williambouet approved these changes

2022-12-12 20:27 UTC, sblondeau requested changes
17 fichiers c'est trop, la registration et l'upload auraient du être séparé en 2, ce qui te fait gagner 5 ou 6 fichiers ^^

2022-12-12 20:27 UTC, sblondeau commented on src/Entity/User.php
> +        message: 'L\'email est incorrect'
pas la peine de traduire en français

2022-12-12 20:27 UTC, sblondeau commented on src/Entity/User.php
> +        pattern: '/\d/',
enlève la regex sur les num de téléphone, inutile de fixer un format, c'est trop restrictif
si je veux mettre 06-06 ou 06 06 ou +336 etc ça ne fonctionne pas...

2022-12-13 10:13 UTC, williambouet submitted a review, later dismissed

2022-12-13 10:56 UTC, sblondeau requested changes

2022-12-13 10:56 UTC, sblondeau commented on src/Form/RegistrationFormType.php
> +                        'message' => 'Please enter a password',
reste qq messages non traduits ici, mais je pense que tu peux enlever le 'message' et tu aura celui par défaut
par contre pense à rajouter le fr dans le fichier config/translation comme montré en LC

2022-12-13 10:56 UTC, sblondeau commented on templates/registration/register.html.twig
> +        <button type="submit" class="btn rounded bg-primary text-light py-2 px-4 mt-4">S'inscrire</button>
ça serait plutot btn btn-primary et pas bg-primary

2022-12-13 10:56 UTC, sblondeau commented on templates/registration/register.html.twig
> +        <button type="submit" class="btn rounded bg-primary text-light py-2 px-4 mt-4">S'inscrire</button>
ça pourrait éventuellement être intéressant de surcharger la classe btn de bootstrap dans ton fichier css principal, pour définir ton style de bouton général et ne pas avoir à mettre 5 autres classes à chaque fois. Tu devrais juste avoir à mettre btn btn-lacouleur
essaie de bien utiliser les variable scss, voir https://getbootstrap.com/docs/5.2/components/buttons/#sass-variables

2022-12-13 10:56 UTC, sblondeau commented on src/Entity/User.php
> +    #[Assert\Length(min: 9)]
le min n'apporte rien à mon sens

2022-12-13 11:32 UTC, williambouet approved these changes

2022-12-13 15:45 UTC, sblondeau approved these changes

2022-12-13 15:45 UTC, merged