S02US11 show profil with fixtures
WildCodeSchool/202209-orleans-php-project-externatic pull request #74
Opened 2022-12-14 13:39 UTC by williambouet

2022-12-14 15:40 UTC, hhertout approved these changes

2022-12-14 15:40 UTC, hhertout commented on src/Controller/CandidateController.php
> +    {
Bah non alors

2022-12-14 16:16 UTC, sblondeau requested changes

2022-12-14 16:16 UTC, sblondeau commented on src/Entity/Candidate.php
> +    private ?string $nationality = null;
je mettrais length de 3, c'est le code ISO des pays que tu vas stocker, (de mémoire c'est 2 ou 3 carac)

2022-12-14 16:16 UTC, sblondeau commented on templates/candidate/index.html.twig
> +{% extends 'base.html.twig' %}
page à retirer non?

2022-12-14 16:16 UTC, sblondeau commented on templates/candidate/show.html.twig
> +							<p>{{ candidate.nationality }}</p>
https://twig.symfony.com/doc/2.x/filters/country_name.html

2022-12-14 16:16 UTC, sblondeau commented on templates/candidate/show.html.twig
> +					<p class="font-title fw-bold m-1">A propos de moi</p>
À (accent)

2022-12-14 16:16 UTC, sblondeau commented on templates/candidate/show.html.twig
> +			<div class="col col-md-6">
le col tout seul est pas en trop ?  idem en dessous

2022-12-14 16:31 UTC, hhertout approved these changes

2022-12-15 08:24 UTC, sblondeau approved these changes

2022-12-15 08:24 UTC, merged