construction de la vue affichant toutes les offres, US01
WildCodeSchool/202209-orleans-php-project-externatic pull request #77
Opened 2022-12-14 17:47 UTC by cedriclv

2022-12-14 20:12 UTC, hhertout requested changes

2022-12-14 20:12 UTC, hhertout commented on assets/styles/_card.scss
> +    background: linear-gradient(180deg, #E9EEF3 0%, rgba(227, 233, 239, 0) 100%);
Peut être à mettre dans une variable $gradient peut-être ?

2022-12-14 22:33 UTC, williambouet commented on assets/styles/_card.scss
> +    //background-color: red;
je pense que tu devras supprimer tes lignes commentées aussi

2022-12-14 22:35 UTC, williambouet commented on templates/component/_card.html.twig
> +<div class="col-12 col-lg-6">
à vérifier, mais je crois que col-12 ne sert à rien

2022-12-14 22:37 UTC, williambouet commented on templates/offer/index.html.twig
> +		<h1 class="d-none">Offres Selectionnées</h1>
sélectionnées

2022-12-14 22:43 UTC, williambouet commented on templates/component/_card.html.twig
> +				<h2 class="fs-4 card-title font-weight-bolder card-offer-title">{{offer.title}}</h2>
ça fonctionne font-weight-bolder ? sinon c'est fw-bolder.

2022-12-15 08:37 UTC, cedriclv commented on assets/styles/_card.scss
> +    //background-color: red;
done

2022-12-15 08:39 UTC, cedriclv commented on templates/component/_card.html.twig
> +<div class="col-12 col-lg-6">
effectivement ;-) done

2022-12-15 08:43 UTC, cedriclv commented on templates/component/_card.html.twig
> +				<h2 class="fs-4 card-title font-weight-bolder card-offer-title">{{offer.title}}</h2>
je l'ai viré, ca doit deja etre dans card-title apparemment ...

2022-12-15 08:48 UTC, cedriclv commented on assets/styles/_card.scss
> +    border-radius: 20px;
done

2022-12-15 08:50 UTC, cedriclv commented on assets/styles/_card.scss
> +    background: linear-gradient(180deg, #E9EEF3 0%, rgba(227, 233, 239, 0) 100%);
done also

2022-12-15 09:06 UTC, hhertout approved these changes

2022-12-15 09:23 UTC, Zakari-B requested changes

2022-12-15 09:23 UTC, Zakari-B commented on src/Entity/Offer.php
> +    private ?\DateTimeImmutable $createdAt = null;
Enlever ? si non nullable, enlever \ puisque importé via use.

2022-12-15 09:23 UTC, Zakari-B commented on src/Entity/Offer.php
> +    #[ORM\Column(length: 255)]
Tous les assert à rajouter.

2022-12-15 09:23 UTC, Zakari-B commented on src/DataFixtures/OfferFixtures.php
> +            $faker = Factory::create();
Pas dans la boucle.

2022-12-15 09:23 UTC, Zakari-B commented on src/Controller/OfferController.php
> +#[Route('/offer')]
rajouter name: app_offer_ et l'enlever des routes.

2022-12-15 09:39 UTC, cedriclv commented on src/Entity/Offer.php
> +    private ?\DateTimeImmutable $createdAt = null;
done

2022-12-15 09:40 UTC, cedriclv commented on src/Entity/Offer.php
> +    #[ORM\Column(length: 255)]
done

2022-12-15 09:40 UTC, cedriclv commented on src/DataFixtures/OfferFixtures.php
> +            $faker = Factory::create();
done

2022-12-15 09:44 UTC, cedriclv commented on src/Controller/OfferController.php
> +#[Route('/offer')]
done

2022-12-15 13:14 UTC, hhertout approved these changes

2022-12-15 14:29 UTC, Zakari-B requested changes

2022-12-15 14:29 UTC, Zakari-B commented on src/Entity/Offer.php
> +    private ?\DateTimeImmutable $targetDate = null;
Encore un antislash qui traine :)

2022-12-15 14:29 UTC, Zakari-B commented on src/Entity/Offer.php
> +    #[Assert\Type(type: Types::INTEGER)]
C'est peut être une bonne idée de vérifier aussi que cet entier soit positif :')

2022-12-15 14:29 UTC, Zakari-B commented on src/Entity/Offer.php
> +    public function getCreatedAt(): ?\DateTimeImmutable
Antislash

2022-12-15 14:29 UTC, Zakari-B commented on src/Entity/Offer.php
> +    public function setCreatedAt(\DateTimeImmutable $createdAt): self
Et la.

2022-12-15 14:29 UTC, Zakari-B commented on src/Entity/Offer.php
> +    public function getTargetDate(): ?\DateTimeImmutable
La aussi.

2022-12-15 14:29 UTC, Zakari-B commented on src/Entity/Offer.php
> +    public function setTargetDate(?\DateTimeImmutable $targetDate): self
Et encore.

2022-12-15 14:29 UTC, Zakari-B commented on src/Form/OfferType.php
> +        $builder
Rajoute les types dans le builder pour s'assurer que symfony ne se trompe pas en le faisant.

2022-12-15 14:29 UTC, Zakari-B commented on templates/component/_card.html.twig
> +
Formatage sans tous ces sauts de ligne, please.

2022-12-15 14:39 UTC, sblondeau commented on assets/styles/app.scss
> +@import "card";
non il ne faut pas que tu importe ce fichier ici, uniquement sur les pages qui en ont besoin
faut que tu créé donc une nouvelle entée addEntrySyle dans webpack.config

2022-12-15 14:39 UTC, sblondeau commented on src/DataFixtures/OfferFixtures.php
> +            $offer->setTitle(self::TITLE_OFFERS[random_int(0, count(self::TITLE_OFFERS) - 1)]);
tu peux utiliser plutot array_rand()

2022-12-15 14:39 UTC, sblondeau commented on src/Entity/Offer.php
> +    #[ORM\Column(length: 255)]
pas très grave, mais pour le coup si sur cette PR tu ne gères que l'affichage, les asserts pouvaient attendre pour la partie Create du CRUD ;-)

2022-12-15 14:39 UTC, sblondeau commented on templates/component/_card.html.twig
> +				<h6 class="fs-4">{{offer.annualWage/1000}}K€/ an
pas de h6 car h2 juste avant

2022-12-15 14:42 UTC, cedriclv commented on src/Entity/Offer.php
> +    private ?\DateTimeImmutable $targetDate = null;
done

2022-12-15 16:09 UTC, cedriclv commented on assets/styles/app.scss
> +@import "card";
done

2022-12-15 16:11 UTC, hhertout approved these changes

2022-12-15 16:17 UTC, hhertout approved these changes

2022-12-16 09:18 UTC, sblondeau requested changes

2022-12-16 09:18 UTC, sblondeau commented on assets/styles/_root.scss
> + $background-gradient:linear-gradient(180deg, #E9EEF3 0%, rgba(227, 233, 239, 0) 100%);
couleur en variable

2022-12-16 09:18 UTC, sblondeau commented on assets/styles/card.scss
> +    font-size: 32px;
font-size peut etre aussi en variable, et en rem c'est mieux

2022-12-16 09:18 UTC, sblondeau commented on src/DataFixtures/OfferFixtures.php
> +            $randomCity = random_int(0, count(self::CITY_OFFERS) - 1);
2 fois randomCity

2022-12-16 09:18 UTC, sblondeau commented on templates/component/_card.html.twig
> +				<h3 class="fs-4">{{offer.annualWage/1000}}K€/ an
installe l'extension twig de vscode si ce n'est pas fait
le formatage automatique t'aidera, là il manque a chaque fois des espaces autour des doubles accolades

2022-12-16 09:39 UTC, cedriclv commented on assets/styles/_root.scss
> + $background-gradient:linear-gradient(180deg, #E9EEF3 0%, rgba(227, 233, 239, 0) 100%);
done

2022-12-16 09:41 UTC, cedriclv commented on assets/styles/card.scss
> +    font-size: 32px;
done

2022-12-16 09:45 UTC, cedriclv commented on src/DataFixtures/OfferFixtures.php
> +            $randomCity = random_int(0, count(self::CITY_OFFERS) - 1);
done

2022-12-16 09:50 UTC, hhertout approved these changes

2022-12-16 09:53 UTC, cedriclv commented on templates/component/_card.html.twig
> +				<h3 class="fs-4">{{offer.annualWage/1000}}K€/ an
done

2022-12-16 09:57 UTC, sblondeau approved these changes

2022-12-16 10:41 UTC, merged