S2US56 Adding Sidebar
WildCodeSchool/202209-orleans-php-project-externatic pull request #84
Opened 2022-12-15 15:05 UTC by hhertout

2022-12-15 16:23 UTC, williambouet approved these changes

2022-12-16 09:42 UTC, williambouet submitted a review, later dismissed

2022-12-16 09:59 UTC, sblondeau approved these changes

2022-12-16 11:01 UTC, Zakari-B requested changes

2022-12-16 11:01 UTC, Zakari-B commented on templates/candidate/show.html.twig
> +			<img class="profilPicture " src="assets/images/Placeholder-pp.png" alt="">
A faire avec le build de webpack encore.

2022-12-16 14:13 UTC, williambouet submitted a review, later dismissed

2022-12-18 23:38 UTC, sblondeau approved these changes

2022-12-19 09:37 UTC, williambouet approved these changes

2022-12-19 10:16 UTC, sblondeau approved these changes

2022-12-19 10:16 UTC, merged