S02US12 added edit profil
WildCodeSchool/202209-orleans-php-project-externatic pull request #87
Opened 2022-12-15 16:16 UTC by williambouet

2022-12-15 16:24 UTC, hhertout approved these changes

2022-12-16 10:06 UTC, sblondeau requested changes

2022-12-16 10:06 UTC, sblondeau commented on src/Entity/Candidate.php
> +        max: 100,
3

2022-12-16 10:06 UTC, sblondeau commented on src/Entity/Candidate.php
> +    #[Assert\NotBlank(message: 'Le champ ne doit pas rester vide.')]
t'amuse pas à personnaliser les messges, garde celui par défaut en fr, idem pour ceux d'en dessous

2022-12-16 10:06 UTC, sblondeau commented on src/Entity/Candidate.php
> +
retour à la ligne en trop

2022-12-16 10:06 UTC, sblondeau commented on src/Form/CandidateType.php
> +                'required' => true,
c'est required true par défaut, donc pas la peine de le spécifier

2022-12-16 10:06 UTC, sblondeau commented on src/Form/CandidateType.php
> +                'attr' => ['class' => 'tinymce',],
sert à quoi cette classe tinymce ?
tu mets beaucoup de class en général sur tes label/input/help 
or sauf exception tu es sensé avoir le meme style sur tous tes forms partout, comme discuté ça serait beaucoup plus simple de surcharger dans le theme.scss pricipal tout ce qui touche aux forms
et tu ajoutes des attributs class dans tes form uniquement pour les qq cas particuiliers éventuels

2022-12-16 10:06 UTC, sblondeau commented on templates/dashboard_layout.html.twig
> +			{% for category, messages in app.flashes %}
vu que tu as mis des icones, c'est très long ce block, ça serait plus lisible de le mettre dans un include de _flashes.html.twig

2022-12-16 13:56 UTC, hhertout submitted a review, later dismissed

2022-12-19 08:29 UTC, sblondeau requested changes

2022-12-19 08:29 UTC, sblondeau commented on src/Controller/CandidateController.php
> +            $this->addFlash('success', 'Votre mise à jour à été prise en compte.');
a été (pas d'accent)

2022-12-19 08:29 UTC, sblondeau commented on src/Form/CandidateType.php
> +                'label' => 'À propose de moi',
propos

2022-12-19 10:04 UTC, hhertout submitted a review, later dismissed

2022-12-19 14:09 UTC, sblondeau approved these changes

2022-12-19 15:29 UTC, hhertout approved these changes

2022-12-19 16:49 UTC, merged