S1US45_part1 Entreprise show by_id
WildCodeSchool/202209-orleans-php-project-externatic pull request #88
Opened 2022-12-15 18:56 UTC by hhertout

TO DO before the link to offer

2022-12-15 19:10 UTC, williambouet commented on templates/company/show.html.twig
> +<div class="container p-4">
Un petit <h1>Entreprise</h1> ?

2022-12-15 19:13 UTC, hhertout commented on templates/company/show.html.twig
> +<div class="container p-4">
Je vais le mettre sur le compagne.name ça fera plus <h1>propre</h1>. 😉

2022-12-15 20:47 UTC, williambouet approved these changes

2022-12-16 10:10 UTC, sblondeau requested changes

2022-12-16 10:10 UTC, sblondeau commented on templates/company/show.html.twig
> +        <a class="btn btn-primary" aria-label="Retour" href="{{ path('app_company_index') }}">Retour</a>
fait en sorte que ton bouton de retour ai pas le meme style que ton bouton Modifier 
tu peux le mettre en outline par ex

2022-12-16 10:10 UTC, sblondeau commented on templates/company/show.html.twig
> +        <a class="btn btn-primary" aria-label="Retour" href="{{ path('app_company_index') }}">Retour</a>
une petite icone en plus peut etre bien aussi

2022-12-16 10:38 UTC, williambouet approved these changes

2022-12-16 10:42 UTC, merged